[tools]
ruff = "latest"
shellcheck = "latest"
yamlfmt = "latest"
yazi = "latest"

[tasks.stow]
description = "Symlink all dotfiles using GNU Stow"
run = """
	@echo "Symlinking dotfiles with stow..."
  description = "Symlink all dotfiles using GNU Stow"
  stow tmux
  stow nvim
  stow emacs
""""

[tasks.provision]
description = "Run Ansible provisioning"
run = """
	@echo "Running Ansible provisioning..."
  ansible-playbook fedora.yml --ask-become-pass
""""
