---
- name: Setup Workstation
  hosts: workstation
  become: true
  gather_facts: true
  tasks:
    - name: Upgrade all packages
      dnf:
        name: "*"
        state: latest
    - name: Install group packages
      dnf:
        name:
          - "@development tools"
          - "@virtualization"
        state: installed
    - name: Add Hashicorp repo for vagrant
      become: yes
      command: sudo dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
    - name: Install extra packages
      dnf:
        name: util-linux
        name: util-linux-user
        name: fish
        name: git
        name: npm
        name: guake
        name: stow
        name: openssl-devel
        name: libtool
        name: wl-clipboard
        name: task
        name: steam-devices
        name: npm
        name: toolbox
        name: marked
        name: llvm
        name: llvm-devel
        name: llvm-cmake-devel
        name: vagrant
    - name: Install Rust/Cargo
      become: yes
      command: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
    - name: Add Cargo to $PATH
      become: yes
      command: fish_add_path ~/.cargo/bin/
    - name: Install Cargo packages
      cargo:
        name: bat
        name: cargo-update
        name: fd-find
        name: lsd
        name: ripgrep
        name: rm-improved
        name: xplr
    # - name: Install Cargo packages
    #   become: yes
    #   command: cargo install cargo-update fd-find lsd ripgrep rm-improved xplr bat
    - name: Add Pip packages to $PATH
      become: yes
      command: fish_add_path ~/.local/bin/
    - name: Install Pip packages
      become: yes
      command: pip install --user youtube-dl tuir thefuck
    - name: Install poetry
      become: yes
      command: curl -sSL https://install.python-poetry.org | python3 -
    - name: Install Doom Emacs
      become: yes
      command: git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.emacs.d\n~/.emacs.d/bin/doom install
    - name: Upgrade Doom (force install)
      become: yes
      command: doom upgrade
    - name: Enable Emacs service in systemd
      become: yes
      command: systemctl enable --user emacs
    - name: Enable Libvirt service in systemd
      become: yes
      command: systemctl enable --user libvirtd
    - name: Add user to libvirt usergroup
      become: yes
      command: sudo gpasswd -a omary libvirt
    - name: Configure Flathub
      become: yes
      command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - name: Install Flatpaks
      flatpak:
        name: org.keepassxc.KeePassXC
        name: com.valvesoftware.steam
        name: com.discordapp.Discord
        name: com.usebottles.bottles
        name: com.valvesoftware.Steam
        name: org.gnome.Podcasts
        name: winehq.Wine.DLLs.dxvk
        name: us.zoom.Zoom
        name: com.valvesoftware.Steam.CompatibilityTool.Proton-Exp
