(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(elfeed-feeds
   '("https://www.androidpolice.com/feed/" "https://lukesmith.xyz/rss.xml" "http://blog.stackoverflow.com/feed/" "http://sethgodin.typepad.com/seths_blog/atom.xml" "https://bunnyman.info/index.xml" "http://blog.dustinkirkland.com/feeds/posts/default" "https://ramonh.dev/blog/feed.xml" "https://anneboyer.substack.com/feed" "https://www.charlieharrington.com/rss.xml" "https://www.hyperborea.org/journal/feed/" "https://100r.co/links/rss.xml" "https://spool-five.com/rss.xml" "https://mwl.io/feed" "https://solar.lowtechmagazine.com/feeds/all-en.atom.xml" "https://cdn.hackernoon.com/feed" "https://blog.codinghorror.com/rss/" "https://krebsonsecurity.com/feed/" "https://www.schneier.com/feed/atom/" "https://www.smashingmagazine.com/feed" "https://martinfowler.com/feed.atom" "https://m.signalvnoise.com/feed/" "http://feeds.hanselman.com/scotthanselman" "https://realpython.com/atom.xml" "http://feeds.feedburner.com/PythonSoftwareFoundationNews" "https://yasoob.me/index.xml" "https://planetpython.org/rss20.xml" "http://coreyms.com/feed/" "http://decafbad.net/feed" "https://nostarch.com/feeds/newbooks.xml" "https://nostarch.com/feeds/comingsoon.xml" "https://inkdroid.org/feed.xml" "https://computer.rip/rss.xml" "https://www.hardill.me.uk/wordpress/feed/" "https://readrust.net/all/feed.rss" "http://xkcd.com/atom.xml" "https://www.smbc-comics.com/comic/rss" "http://feeds.feedburner.com/seriouseatsfeaturesvideos" "http://feeds.feedburner.com/ItsFoss" "https://hacks.mozilla.org/feed/" "https://planet.kde.org/index.xml" "https://www.guildwars2.com/en/feed/" "https://www.teamfortress.com/rss.xml" "https://www.gamingonlinux.com/article_rss.php" "https://www.thebioneer.com/feed/" "https://startingstrength.com/rss.rss" "https://fx-companion.com/feed/" "https://www.democracynow.org/democracynow.rss" "https://www.hexbear.net/feeds/all.xml?sort=Active" "https://lobste.rs/rss" "https://network23.org/ainriail/feed/" "https://feeds.feedburner.com/TheHackersNews" "https://bluelabyrinths.com/feed/" "https://habermas-rawls.blogspot.com/feeds/posts/default?alt=rss" "https://www.lacan.com/perfumeblog/?feed=rss2" "https://www.urbanomic.com/feed/" "https://aeon.co/feed.rss" "https://www.3ammagazine.com/3am/feed/" "https://www.jamesrwilliams.net/feed/")))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
