# "$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio = [1, 3, 4]
linemode = "size"
show_hidden = true

[[plugin.prepend_fetchers]]
id = "git"
mime = "*"
run = "git"
group = "render"

[preview]
image_previewer = "chafa"
max_width = 1920
max_height = 1080

[opener]
image = [{ run = 'xdg-open %s', desc = "Open", orphan = true }]
neovide-fallback = [
  { run = 'neovide %s || ${EDITOR:-vi} %s', desc = "Neovide", block = false, orphan = true, for = "unix" },
]
play = [
  { run = 'celluloid %s', desc = "Play", block = false, orphan = true, for = "unix" },
]

[open]
prepend_rules = [
  { mime = "image/*", use = "image" },
  { mime = "text/*", use = "neovide-fallback" },
  { mime = "video/*", use = "play" },
  { mime = "application/gzip", use = "open" },
  { mime = "application/x-tar", use = "open" },
  { mime = "application/zip", use = "open" },
  { mime = "application/x-7z-compressed", use = "open" },
  { mime = "*", use = "neovide-fallback" },
]
