import = ["/home/omary/.config/alacritty/dracula.toml"]
tabspaces = 4

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
live_config_reload = true
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold"

[font.italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 9001

[shell]
args = ["-c", "tmux attach || tmux"]
program = "/usr/bin/zsh"

[shell.url.launcher]
args = []
program = "xdg-open"

[visual_bell]
duration = 0

[window]
decorations = "full"
dynamic_padding = true
startup_mode = "Windowed"
title = "Alacritty"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 2
y = 2
