[tools]
"aqua:tealdeer-rs/tealdeer" = "1.8.1"
aube = "1.38.1"
"navi" = "2.24.0"
node = "26.7.0"
pre-commit = "4.6.2"
python = "3.14.7"
rtk = "0.45.0"
ruff = "0.16.2"
trufflehog = "3.96.0"

[settings]
experimental = true
